# Numpy
- Numerical python ,popularly known as numpy ,has been designed to carry out mathematical computation faster and easier rate
- Numpy provides a large library of high level mathematical functions to operate on these functions
- Data structures like mutlidimensional dimensional arrays beyond matrices and linear arrays

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

In [4]:
arr=np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [5]:
arr.ndim # returns the dimension

1

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr1=np.array([1,2,3,4,"apssdc"])
type(arr1)

numpy.ndarray

In [8]:
arr1.dtype

dtype('<U11')

In [9]:
np.array("4-8-2020")

array('4-8-2020', dtype='<U8')

- b = boolean
- i = signed integer
- u =unsigned integer
- f = float
- c =complex
- U = unicode
- O = objects

In [10]:
s= np.array(4+5j)
s.dtype

dtype('complex128')

In [13]:
np.arange(1,11) #to create array from particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [15]:
f=np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
f.shape

(50,)

In [17]:
f.ndim

1

In [18]:
f.reshape(10,5) # reshaping the array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [19]:
f.reshape(5,-1) # default number of columns,-1 used for default

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [20]:
f.reshape(-1,10) # default number of rows 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [21]:
f.reshape(-1,-1) # it is error

ValueError: can only specify one unknown dimension

In [23]:
f.reshape(4,10) #error
# number of elements must fit in the reshape size


ValueError: cannot reshape array of size 50 into shape (4,10)

In [24]:
arr4=np.arange(0,50).reshape(5,1,10)
arr4

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [25]:
arr4.shape

(5, 1, 10)

In [26]:
arr4.ndim # 3d array which is tensor

3

In [27]:
arr4[1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [28]:
arr4.dtype

dtype('int32')

In [29]:
np.arange(0,100).reshape(10,1,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [30]:
a=np.arange(0,100).reshape(2,5,10) 
# first is number of matices 
# next are rows and columns with that number of matrices

In [31]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [32]:
arr3d=np.arange(0,40).reshape(2,2,10)
arr3d # 2 matrices with 2 rows and 10 columns

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]])

In [33]:
arr3d.ndim

3

In [35]:
np.linspace(0,10,100) # points with space of 100 ,i.e pointwise

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [36]:
print(dir(np)) # method

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [37]:
# we can use help 
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [38]:
np.ones(2)

array([1., 1.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((3,3),dtype=object)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=object)

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.eye(3,3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Adding and sorting elements

In [45]:
a=np.array([1,4,2,16,6,7])
a

array([ 1,  4,  2, 16,  6,  7])

In [46]:
np.sort(a) # sorted manner

array([ 1,  2,  4,  6,  7, 16])

In [47]:
# descending order
-np.sort(-a)

array([16,  7,  6,  4,  2,  1])

In [48]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [56]:
surnames=("ad","abc","dfg")
first_names=("aadi","akhil","manu")
ind=np.lexsort((first_names,surnames)) # sort by using surnames and then names
ind

array([1, 0, 2], dtype=int64)

In [57]:
[surnames[i]+""+first_names[i] for i in ind] # sorted based on surnames

['abcakhil', 'adaadi', 'dfgmanu']

In [60]:
a=np.array([[1,4],[3,1]])
np.sort(a) # sort a long axis

array([[1, 4],
       [1, 3]])

In [61]:
a

array([[1, 4],
       [3, 1]])

In [62]:
np.sort(a,axis=0)

array([[1, 1],
       [3, 4]])

In [63]:
np.sort(a,axis=1)

array([[1, 4],
       [1, 3]])

In [65]:
a=np.array([12,1,2,45,90.4,90.4])

In [70]:
a

array([12. ,  1. ,  2. , 45. , 90.4, 90.4])

In [74]:
#partition:  creates a array with its elements rearranged in such a way that the value  of the element in the kth position
#is in the position it would be in the sorted array

np.partition(a,2) 

array([ 1. ,  2. , 12. , 45. , 90.4, 90.4])

In [75]:
a=np.array([3,4,2,1,34,6,17,45,22,78])
np.partition(a,2)

array([ 1,  2,  3,  4, 34,  6, 17, 45, 22, 78])

In [79]:
a=np.arange(1,5)
b=np.arange(6,10)
np.concatenate((a,b)) # adding the 2nd array to 1st array last 

array([1, 2, 3, 4, 6, 7, 8, 9])

# Masking

In [2]:
import numpy as np

In [3]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[a%2==0]

array([2, 4, 6, 8])

In [4]:
c=a[(a>3)&(a<7)]
print("between 3 & 7",c)

between 3 & 7 [4 5 6]


In [6]:
c=a[(a>5) | (a==5)]
c

array([5, 6, 7, 8, 9])

## Indexing

In [7]:
f=np.arange(1,100,2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
f[1:20]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

In [9]:
f[8]

17

In [10]:
f[::-1] # sequence of nth item from last

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [11]:
f[::1] # sequence of each nth item in entire sequence

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [12]:
f[::3]

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [13]:
f=np.arange(1,100)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
f[1:20]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [15]:
f[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
f[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
f[::3] # 3rd index item fromlist

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

## Mathematical Function

In [18]:
a=np.arange(1,4)
b=np.array([23,12,45])
print(a+b)

[24 14 48]


In [19]:
a-b

array([-22, -10, -42])

In [20]:
a/b

array([0.04347826, 0.16666667, 0.06666667])

In [21]:
a%b

array([1, 2, 3], dtype=int32)

In [22]:
np.divide(a,b)

array([0.04347826, 0.16666667, 0.06666667])

In [23]:
np.remainder(a,b)

array([1, 2, 3], dtype=int32)

In [24]:
a.sum

<function ndarray.sum>

In [25]:
a.sum()

6

In [26]:
b.sum()

80

In [27]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [28]:
a.sum()

10

In [29]:
a.sum(axis=1) # row sum

array([3, 7])

In [30]:
a.sum(axis=0) # column wise sum

array([4, 6])

In [31]:
# log and exp
np.log(2)

0.6931471805599453

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [34]:
np.log10(a)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [35]:
np.log2(10)

3.321928094887362

In [36]:
np.log2(a)

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [37]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

# Rounding Functions

In [38]:
a= np.array([-1.7,2.3,4.5,-8.9,6.2])
a

array([-1.7,  2.3,  4.5, -8.9,  6.2])

In [39]:
np.round(a)

array([-2.,  2.,  4., -9.,  6.])

In [40]:
np.floor(a)

array([-2.,  2.,  4., -9.,  6.])

In [41]:
np.ceil(a)

array([-1.,  3.,  5., -8.,  7.])

## Random

In [42]:
from numpy import random

In [43]:
random.randint(100)

22

In [44]:
random.randint(100) # for every output we get different value

18

In [45]:
random.rand(10)

array([0.48354827, 0.25135408, 0.742155  , 0.6714188 , 0.90474506,
       0.60290246, 0.90066672, 0.25368289, 0.34286876, 0.93379975])

In [46]:
random.choice(["a","c","m","d"])

'd'

 - STATISTICAL FUNCTIONS

In [47]:
import numpy as np

In [48]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [49]:
arr.sum()

100

In [50]:
arr1=np.array([[0,10,20],[20,45,67],[23,45,67]])
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [51]:
arr1.sum()

297

In [52]:
arr1.sum(axis=0)

array([ 43, 100, 154])

In [53]:
arr1.sum(axis=1)

array([ 30, 132, 135])

In [54]:
arr1.sum(0)

array([ 43, 100, 154])

In [55]:
print(np.average(arr))
print(np.average(arr1))

25.0
33.0


In [56]:
np.average(arr,axis=0)

25.0

In [57]:
np.average(arr,0)

25.0

In [58]:
#product
np.prod(arr)

240000

In [59]:
arr

array([10, 20, 30, 40])

In [60]:
np.prod(arr1)

0

In [61]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [62]:
np.prod(arr1,0)

array([    0, 20250, 89780])

In [63]:
np.product(arr1,axis=1)

array([    0, 60300, 69345])

In [64]:
#minimum
print(arr.min())
print(arr1.min())

10
0


In [65]:
arr1.min(1)

array([ 0, 20, 23])

In [66]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [67]:
arr1.min(0)

array([ 0, 10, 20])

In [68]:
#maximum
arr.max()

40

In [69]:
arr1.max()

67

In [70]:
arr1.max(0)

array([23, 45, 67])

In [71]:
arr.mean()

25.0

In [72]:
arr.mean(0)

25.0

In [73]:
arr1.mean(1)

array([10., 44., 45.])

In [74]:
np.median(arr1)

23.0

In [75]:
np.median(arr1,0)

array([20., 45., 67.])

In [76]:
from statistics import mode

In [77]:
help(mode)

Help on function mode in module statistics:

mode(data)
    Return the most common data point from discrete or nominal data.
    
    ``mode`` assumes discrete data, and returns a single value. This is the
    standard treatment of the mode as commonly taught in schools:
    
    >>> mode([1, 1, 2, 3, 3, 3, 3, 4])
    3
    
    This also works with nominal (non-numeric) data:
    
    >>> mode(["red", "blue", "blue", "red", "green", "red", "red"])
    'red'
    
    If there is not exactly one most common value, ``mode`` will raise
    StatisticsError.



In [78]:
mode([1,1,2,3,3,3,3,4,4,4])

3

In [79]:
#variance
arr1.var()

517.3333333333334

In [80]:
arr.std()

11.180339887498949

In [81]:
arr1.std()

22.744962812309307

In [82]:
arr

array([10, 20, 30, 40])

In [83]:
#cumulative sum
arr1.cumsum()

array([  0,  10,  30,  50,  95, 162, 185, 230, 297], dtype=int32)

In [84]:
arr1.cumsum(1)

array([[  0,  10,  30],
       [ 20,  65, 132],
       [ 23,  68, 135]], dtype=int32)

In [85]:
arr.cumprod() # cumulative product

array([    10,    200,   6000, 240000], dtype=int32)

- Aggregation

In [86]:
arr

array([10, 20, 30, 40])

In [87]:
arr.argmin()

0

In [88]:
arr[arr.argmin()]

10

In [89]:
arr1.argmin(1)

array([0, 0, 0], dtype=int64)

In [90]:
arr1.argmin(0)

array([0, 0, 0], dtype=int64)

In [91]:
arr[1]

20

In [92]:
arr1.argmin()

0

In [93]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [94]:
# to find the  index of particular value
result=np.where(arr==40)
result

(array([3], dtype=int64),)

In [95]:
print(arr1.argmin())

0


In [96]:
arr1[0]

array([ 0, 10, 20])

In [97]:
arr1[0][1]

10

In [98]:
arr1[1]

array([20, 45, 67])

In [99]:
arr1[1][0]

20

In [100]:
#correlation coefficient
np.corrcoef(arr)

1.0

In [101]:
np.corrcoef(arr1)

array([[1.        , 0.99932165, 1.        ],
       [0.99932165, 1.        , 0.99932165],
       [1.        , 0.99932165, 1.        ]])

- Filtering 

In [102]:
arr2=np.arange(110)

In [103]:
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109])

In [104]:
arr2[-20:]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109])

In [105]:

a=np.arange(100)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [106]:
arr[arr>10]

array([20, 30, 40])

- fromiter :

 creates one new 1-dimensional array from an iterable object

In [71]:
iter=(x*x for x in range(5) for y in range(10) if y<x)
np.fromiter(iter,float)

array([ 1.,  4.,  4.,  9.,  9.,  9., 16., 16., 16., 16.])

In [109]:
for x in range(5):
    for y in range(10):
        if y<x:
            print(x*x)
            

1
4
4
9
9
9
16
16
16
16
